### ISSUE TITLE
Attempt to run a command prompt command if on windows and process fails to start

### ISSUE THREAD

**Issue by damianh** [adamralph/simple-exec#99] opened 2019-01-01 16:29 UTC
We have this code in our build at https://github.com/SQLStreamStore/SQLStreamStore.HAL/blob/f3bfa641154b7c0a82c0d94e1ddec9ffd6c8c774/build/Program.cs#L131-L134

```csharp
if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
    Run("cmd", "/c yarn", workingDirectory);
else
    Run("yarn", args, workingDirectory);
```

I'd rather just write 

```csharp
Run("yarn", args, workingDirectory);
```

But running that results in an exception on windows:

```
Bullseye/build-hal-docs: System.ComponentModel.Win32Exception (2): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SimpleExec.ProcessExtensions.EchoAndStart(Process process, Boolean noEcho) in C:\projects\simple-exec\SimpleExec\ProcessExtensions.cs:line 33
   at SimpleExec.Command.Run(String name, String args, String workingDirectory, Boolean noEcho) in C:\projects\simple-exec\SimpleExec\Command.cs:line 29
   at build.Program.<>c.<Main>b__6_0() in E:\dev\damianh\SQLStreamStore\build\Program.cs:line 22
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Bullseye.Internal.ActionTarget.RunAsync(Boolean dryRun, Boolean parallel, Logger log, Func`2 messageOnly) in C:\projects\bullseye\Bullseye\Internal\ActionTarget.cs:line 25
```

Suggestion: on windows, catch this and then attempt `Run("cmd", $"/c {name} {arg}", workingDirectory);` ?

**Comment by damianh** [comment] 2019-01-01 16:30
Added this to my code (not sure about the method name, but what-evs):

```csharp
        static void RunCmd(string name, string args = null, string workingDirectory = null, bool noEcho = false)
        {
            try
            {
                Run(name, args, workingDirectory, noEcho);
            }
            catch (Win32Exception ex) when (ex.NativeErrorCode == 2) // The system cannot find the file specified.
            {
                var cmdArgs = $"/C {name}";
                if (args != null)
                {
                    cmdArgs += " " + args;
                }
                Run("cmd", cmdArgs, workingDirectory, noEcho);
            }
        }
```

**Comment by adamralph** [comment] 2019-01-01 16:42
@damianh what is the root cause of not being able to run `yarn` on Windows without `cmd`?

**Comment by adamralph** [comment] 2019-01-01 17:54
FTR this was discusses at great length in [Slack](https://ddd-cqrs-es.slack.com/archives/C3GTBRMS7/p1546359264036100).

**Comment by adamralph** [comment] 2019-01-03 17:19
Closing in favour of #100

**Closed by adamralph** 2019-01-03 17:19 UTC
Labels: wontfix
