### ISSUE TITLE
Linux & child process

### ISSUE THREAD

**Issue by mihaimyh** [adamralph/simple-exec#406] opened 2022-02-07 20:04 UTC
First of all, thank you for this library, it really make things much easier to work with processes.
I am using this library on Linux to run different kind of commands and shell scripts. I noticed that running a Bash script in Linux, which actually will start a background application, will create that application as a child to my .NET app.

The problem is, if I am stopping my .NET it kill also the child. Any way to prevent child processes getting killed?

Not sure if it helps, since I am not understanding the exact use of it, but I have `createNoWindow: true`. According to https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=net-6.0 this property is ignored on Linux.

**Comment by adamralph** [comment] 2022-02-10 19:23
I'm afraid SimpleExec isn't designed for uses cases which involves spawning independent processes. SimpleExec is designed to start a process and wait for it to exit, optionally reading the output and error streams. The behaviour you are describing is expected. If the process calling SimpleExec is killed then any child processes will also be killed. You may want to look into other packages for your use cases, such as [LittleForker](https://github.com/damianh/LittleForker).

I'm closing this and marking it _invalid_, because it is not a bug.

**Closed by adamralph** 2022-02-10 19:23 UTC
Labels: bug, invalid
